// MIT and ISC require their copyright notice to travel with copies and
// Apache-2.0 requires a copy of the licence, but a bundler strips comments, so
// the built app satisfies none of that on its own.

import { readFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";

const LICENCE_FILE = /^(licen[cs]e|copying|notice)(\.(md|txt))?$/i;

// npm hoists, but a nested copy can be a different version under a different
// licence, so walk up the way Node's own resolution does.
function findPackageDir(name, fromDir) {
  let current = fromDir;
  for (;;) {
    const candidate = join(current, "node_modules", name);
    if (existsSync(join(candidate, "package.json"))) {
      return candidate;
    }
    const parent = dirname(current);
    if (parent === current) {
      return null;
    }
    current = parent;
  }
}

const readManifest = (dir) =>
  JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));

function licenceText(dir) {
  const file = readdirSync(dir).find((entry) => LICENCE_FILE.test(entry));
  return file ? readFileSync(join(dir, file), "utf8").trim() : null;
}

function licenceName(manifest) {
  if (typeof manifest.license === "string") return manifest.license;
  if (manifest.license?.type) return manifest.license.type;
  if (Array.isArray(manifest.licenses)) {
    return manifest.licenses.map((entry) => entry.type ?? entry).join(" OR ");
  }
  return null;
}

// The `dependencies` tree only: devDependencies never reach a user, and the one
// optionalDependency is @napi-rs/canvas, which pdf.js reaches through
// createRequire, so the specifier is bundled but the package's code is not.
export function collectThirdPartyPackages(repoRoot) {
  const collected = new Map();
  const missing = [];

  const collect = (name, fromDir) => {
    const dir = findPackageDir(name, fromDir);
    if (!dir) {
      missing.push(`${name} (could not be resolved from ${fromDir})`);
      return;
    }

    const manifest = readManifest(dir);
    const key = `${manifest.name}@${manifest.version}`;
    if (collected.has(key)) {
      return;
    }

    const text = licenceText(dir);
    const licence = licenceName(manifest);
    if (!text && !licence) {
      missing.push(`${key} (no licence file and no license field)`);
    }

    const repository =
      typeof manifest.repository === "string"
        ? manifest.repository
        : manifest.repository?.url;

    collected.set(key, {
      name: manifest.name,
      version: manifest.version,
      licence,
      homepage: manifest.homepage ?? repository ?? null,
      text,
    });

    for (const dependency of Object.keys(manifest.dependencies ?? {})) {
      collect(dependency, dir);
    }
  };

  const root = readManifest(repoRoot);
  for (const dependency of Object.keys(root.dependencies ?? {})) {
    collect(dependency, repoRoot);
  }

  // Sorted so a rebuild that changes nothing produces an identical file.
  const packages = [...collected.values()].sort((left, right) =>
    `${left.name}@${left.version}`.localeCompare(
      `${right.name}@${right.version}`,
    ),
  );

  return { packages, missing };
}

// Licence texts go in fenced blocks so their own wrapping survives.
export function renderNotices(projectName, packages) {
  const header = [
    `# ${projectName} - third-party notices`,
    "",
    "This application bundles the open-source packages listed below. Each is",
    "reproduced with its own licence text, as those licences require.",
    "",
    "Generated by `scripts/prepare-renderer-assets.mjs` from the production",
    "dependency tree. Build tooling is not distributed and is not listed here;",
    "`workbox-precaching` is a production dependency because its code ships,",
    "inside the service worker.",
    "",
    `## ${packages.length} packages`,
    "",
    ...packages.map(
      (entry) =>
        `- ${entry.name}@${entry.version} (${entry.licence ?? "see text"})`,
    ),
  ].join("\n");

  const body = packages
    .map((entry) =>
      [
        `## ${entry.name}@${entry.version}`,
        "",
        entry.licence ? `Licence: ${entry.licence}` : null,
        entry.homepage
          ? `Source: <${entry.homepage.replace(/^git\+/, "")}>`
          : null,
        "",
        "```",
        entry.text ?? `(no licence file shipped; declared as ${entry.licence})`,
        "```",
      ]
        .filter((line) => line !== null)
        .join("\n"),
    )
    .join("\n\n");

  return `${header}\n\n${body}\n`;
}
